print('hi')
print('hi')
print('hi')
print('hi')
print('hello')
print('Peter!!!!!!!!')
print('John is a gay!!!!!!')
print('Brian is a dog')
print('Lois and Peter are couple')
print('Quagmire and Peter are couple')
print('John and Peter are couple')

